### ISSUE TITLE
osx releases

### ISSUE THREAD

**Issue by mrigger** [graalvm/openjdk8-jvmci-builder#5]
Would it be possible to add osx releases for JVMCI versions starting from 0.17? I want to add [a osx gate in Sulong](https://github.com/graalvm/sulong/pull/394), which would be made easier by having such releases.

**Comment by dougxc** [comment]
Unfortunately, I can't see an easy way to do this. Building a JVMCI JDK8 binary requires an OpenJDK8 binary to begin with. As far as I know, there are no reliable OpenJDK8 binaries available for osx.
